
name: fastapi-template

services:
  auth-dev:
    build: .
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      # Монтируем код для мгновенного hot-reload
      - ./src:/app/src:rw
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
    command: sh -c "
        alembic upgrade head && uvicorn src.main:app 
        --host 0.0.0.0 
        --port 8000 
        --reload 
        --reload-dir src
        "
    ports:
      - "8000:8000"
    depends_on:
      auth-postgres-dev:
        condition: service_healthy
      auth-redis-dev:
        condition: service_started
    networks:
      - backend

  auth-postgres-dev:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  auth-redis-dev:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server
      --appendonly yes
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data_dev:/data
    networks:
      - backend

  # === Удобные GUI-инструменты ===
  auth-adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      ADMINER_DEFAULT_SERVER: auth-postgres-dev
    depends_on:
      - auth-postgres-dev
    networks:
      - backend

  auth-pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    env_file:
      - .env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - auth-postgres-dev
    networks:
      - backend

volumes:
  postgres_data_dev:
  redis_data_dev:
  pgadmin_data:

networks:
  backend:
    driver: bridge
